sudo: false
language: scala
scala:
- 2.10.5
- 2.11.6
jdk:
- oraclejdk7
script:
- sbt -Dfile.encoding=UTF8 -no-colors ++$TRAVIS_SCALA_VERSION test
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
notifications:
  hipchat:
    rooms:
      secure: EUZKNeVm/W1klTwTVFKiTgC4NaASokm+UZMkZkzWxkuQtQGpSkGRqBi1u0ASsptklg5+srHU+Y6MqKfMAuYoV0scB1ihlfMWw81L5ssZmg8T2enm8rEXmq+XkDa/uITZEKNps7ajhchhW2ti+7Vg6v9sW1ckSn7tkWJSfFVJlx4=
